on:
  push:
    tags:
      - "v[12].[0-9]+.[0-9]+-beta.[0-9]+"

name: "Unstable Tag"

permissions:
  contents: read

jobs:
  build:
    name: "Build"

    uses: ./.github/workflows/part_build.yml

  docs:
    name: "Docs"

    uses: ./.github/workflows/part_docs.yml

  release:
    name: Create Release

    needs: ["build", "docs"]

    permissions:
      contents: write

    uses: ./.github/workflows/part_release.yml
    with:
      releaseName: "${{ github.ref_name }}"
      stable: false
